### ISSUE TITLE
"Half stars" not working although set ".half" class 

### ISSUE THREAD

**Issue by greenwind1202** [BioPhoton/css-star-rating#28]
First of all, thanks for your library. Its awesome and I really like it.
But when I tried to your demo as below, although ".half" class is set, rating value does not have a half star at the end. 
```
<div class="rating large star-icon direction-rtl value-1 half color-default label-top">
   <div class="label-value">1.5</div>
    <div class="star-container">
        <div class="star">
            <i class="star-empty"></i>
            <i class="star-half"></i>
            <i class="star-filled"></i>
        </div>
        <div class="star">
            <i class="star-empty"></i>
            <i class="star-half"></i>
            <i class="star-filled"></i>
        </div>
        <div class="star">
            <i class="star-empty"></i>
            <i class="star-half"></i>
            <i class="star-filled"></i>
        </div>
    </div>
</div>
```
I also attach output when run above html code. 
![output](https://user-images.githubusercontent.com/12084475/29906909-796d7468-8e42-11e7-937b-48e8963b142c.PNG)
Did I miss something? Please help me to resolved it.

Thanks and best regards,

**Comment by BioPhoton** [comment]
take a look at the css doc. I put it online now => https://biophoton.github.io/css-star-rating/section-1.html

Hope this helps.
best Michael

**Comment by leoplct** [comment]
Same problem. I cannot figure out from documentation how to solve
