### ISSUE TITLE
compound selector no longer extend

### ISSUE THREAD

**Issue by webcat12345** [BioPhoton/css-star-rating#44]
```
Module build failed (from ./node_modules/sass-loader/lib/loader.js):

      @extend .star.direction-rtl;
             ^
      Compound selectors may no longer be extended.
Consider `@extend .star, .direction-rtl` instead.
See http://bit.ly/ExtendCompound for details.

    ╷
297 │       @extend .star.direction-rtl;
    │               ^^^^^^^^^^^^^^^^^^^
    ╵
  node_modules/css-star-rating/scss/_elements.scss 297:15  root stylesheet
```

**Comment by elkarouani** [comment]
Same problem, waiting long time for response, then i just uninstall this package and making a custom star rating component

**Comment by burner-account** [comment]
Can confirm, using angular 10,
```
    "angular-star-rating": "^4.0.0-beta.3",
    "css-star-rating": "^1.2.4",
```

**Comment by AncaorDev** [comment]
> ```
> Module build failed (from ./node_modules/sass-loader/lib/loader.js):
> 
>       @extend .star.direction-rtl;
>              ^
>       Compound selectors may no longer be extended.
> Consider `@extend .star, .direction-rtl` instead.
> See http://bit.ly/ExtendCompound for details.
> 
>     ╷
> 297 │       @extend .star.direction-rtl;
>     │               ^^^^^^^^^^^^^^^^^^^
>     ╵
>   node_modules/css-star-rating/scss/_elements.scss 297:15  root stylesheet
> ```

use : npm install node-sass@4.14.1

**Comment by sushan05** [comment]
Any update on this.
I would not want to switch to `node-sass` from `sass`

**Comment by helping083** [comment]
Still the same problem.
Looks like this package isn't supported.

**Comment by billyjov** [comment]
Fix in the latest version
